In [40]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [6]:
df = np.round(pd.read_csv("50_Startups.csv")[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)

In [7]:
df.head()

,R&D Spend,Administration,Marketing Spend,Profit
0,17.0,14.0,47.0,19.0
1,16.0,15.0,44.0,19.0
2,15.0,10.0,41.0,19.0
3,14.0,12.0,38.0,18.0
4,14.0,9.0,37.0,17.0


In [11]:
df = df.iloc[:,0:-1] # from 0 index column all rows and removing last 1`

In [13]:
df.head()

,R&D Spend,Administration,Marketing Spend
0,17.0,14.0,47.0
1,16.0,15.0,44.0
2,15.0,10.0,41.0
3,14.0,12.0,38.0
4,14.0,9.0,37.0


In [17]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

/tmp/ipykernel_5751/766688332.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
/tmp/ipykernel_5751/766688332.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
/tmp/ipykernel_5751/766688332.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan


In [18]:
df.isnull().sum()

R&D Spend          1
Administration     1
Marketing Spend    1
dtype: int64

In [23]:
df.head()

,R&D Spend,Administration,Marketing Spend
0,17.0,14.0,47.0
1,NaN,15.0,44.0
2,15.0,10.0,41.0
3,14.0,NaN,38.0
4,14.0,9.0,37.0


In [26]:
# step 1 impute all values with mean of the specifc column

dfo = pd.DataFrame()

dfo["R&D Spend"] = df["R&D Spend"].fillna(df["R&D Spend"].mean())
dfo["Administration"] = df["Administration"].fillna(df["Administration"].mean())
dfo["Marketing Spend"] =  df["Marketing Spend"].fillna(df["Marketing Spend"].mean())

In [29]:
dfo.head()

,R&D Spend,Administration,Marketing Spend
0,17.000000,14.000000,47.0
1,7.163265,15.000000,44.0
2,15.000000,10.000000,41.0
3,14.000000,12.163265,38.0
4,14.000000,9.000000,37.0


In [31]:
dfo.isnull().sum() # 0th Iteration

R&D Spend          0
Administration     0
Marketing Spend    0
dtype: int64

In [33]:
df1 = dfo.copy() # now come to 1st iteration

df1.iloc[1,0] = np.nan
df1.head()

,R&D Spend,Administration,Marketing Spend
0,17.0,14.000000,47.0
1,NaN,15.000000,44.0
2,15.0,10.000000,41.0
3,14.0,12.163265,38.0
4,14.0,9.000000,37.0


In [35]:
# now we select specifc rows other then missing to train our model

x = df1.iloc[[0,2,3,4],[1,2]] # x input features 

In [36]:
x

,Administration,Marketing Spend
0,14.000000,47.0
2,10.000000,41.0
3,12.163265,38.0
4,9.000000,37.0


In [37]:
y = df1.iloc[[0,2,3,4],0]

In [41]:
y

0    17.0
2    15.0
3    14.0
4    14.0
Name: R&D Spend, dtype: float64

In [42]:
lr = LinearRegression()
lr.fit(x,y)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [44]:
lr.predict(df1.iloc[1,1:].values.reshape(1,2)) # pick first column full first row for prediction then convert to numpy array and then convet to 2D array

/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([15.90294324])

In [45]:
df1.iloc[1,0] = 15.9


In [47]:
df1.head()

,R&D Spend,Administration,Marketing Spend
0,17.0,14.000000,47.0
1,15.9,15.000000,44.0
2,15.0,10.000000,41.0
3,14.0,12.163265,38.0
4,14.0,9.000000,37.0


In [48]:
df1.iloc[3,1] = np.nan

In [50]:
df1.head()

,R&D Spend,Administration,Marketing Spend
0,17.0,14.0,47.0
1,15.9,15.0,44.0
2,15.0,10.0,41.0
3,14.0,NaN,38.0
4,14.0,9.0,37.0


In [51]:
x = df1.iloc[[0,1,2,4],[0,2]]

In [52]:
x

,R&D Spend,Marketing Spend
0,17.0,47.0
1,15.9,44.0
2,15.0,41.0
4,14.0,37.0


In [53]:
y = df1.iloc[[0,1,2,4],[0]]

In [54]:
y

,R&D Spend
0,17.0
1,15.9
2,15.0
4,14.0


In [55]:
lr2 = LinearRegression()

lr2.fit(x,y)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [56]:
lr2.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[14.]])

In [57]:
df1.iloc[3,1] = 14.0

In [60]:
df1.head()

,R&D Spend,Administration,Marketing Spend
0,17.0,14.0,47.0
1,15.9,15.0,44.0
2,15.0,10.0,41.0
3,14.0,14.0,38.0
4,14.0,9.0,37.0


In [61]:
df

,R&D Spend,Administration,Marketing Spend
0,17.0,14.0,47.0
1,NaN,15.0,44.0
2,15.0,10.0,41.0
3,14.0,NaN,38.0
4,14.0,9.0,37.0
5,13.0,10.0,36.0
6,13.0,15.0,13.0
7,13.0,15.0,32.0
8,12.0,15.0,31.0
9,12.0,11.0,30.0


In [62]:
df1.iloc[49,2] = np.nan

In [63]:
df1

,R&D Spend,Administration,Marketing Spend
0,17.0,14.0,47.0
1,15.9,15.0,44.0
2,15.0,10.0,41.0
3,14.0,14.0,38.0
4,14.0,9.0,37.0
5,13.0,10.0,36.0
6,13.0,15.0,13.0
7,13.0,15.0,32.0
8,12.0,15.0,31.0
9,12.0,11.0,30.0


In [69]:
x = df1.iloc[0:49,[0,1]]

In [70]:
x

,R&D Spend,Administration
0,17.0,14.0
1,15.9,15.0
2,15.0,10.0
3,14.0,14.0
4,14.0,9.0
5,13.0,10.0
6,13.0,15.0
7,13.0,15.0
8,12.0,15.0
9,12.0,11.0


In [71]:
y = df1.iloc[0:49,2]

In [72]:
y

0     47.0
1     44.0
2     41.0
3     38.0
4     37.0
5     36.0
6     13.0
7     32.0
8     31.0
9     30.0
10    23.0
11    25.0
12    25.0
13    25.0
14    26.0
15    26.0
16    26.0
17    28.0
18    29.0
19     0.0
20    30.0
21    30.0
22    30.0
23    30.0
24    14.0
25    14.0
26    13.0
27    35.0
28    12.0
29    11.0
30     9.0
31     9.0
32     5.0
33    21.0
34    21.0
35    21.0
36    20.0
37    20.0
38    19.0
39    17.0
40    17.0
41    16.0
42    15.0
43     4.0
44     3.0
45     0.0
46    30.0
47     0.0
48     0.0
Name: Marketing Spend, dtype: float64

In [73]:
lr3 = LinearRegression()

In [74]:
lr3.fit(x,y)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [75]:
lr3.predict(df1.iloc[49,[0,1]].values.reshape(1,2))

/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5.99482793])

In [76]:
df1.iloc[49,2] = 5.99

In [77]:
df1

,R&D Spend,Administration,Marketing Spend
0,17.0,14.0,47.00
1,15.9,15.0,44.00
2,15.0,10.0,41.00
3,14.0,14.0,38.00
4,14.0,9.0,37.00
5,13.0,10.0,36.00
6,13.0,15.0,13.00
7,13.0,15.0,32.00
8,12.0,15.0,31.00
9,12.0,11.0,30.00


In [79]:
# 1 iteration or 0 iteration done lets subtract

df1 - dfo

,R&D Spend,Administration,Marketing Spend
0,0.000000,0.000000,0.000000
1,8.736735,0.000000,0.000000
2,0.000000,0.000000,0.000000
3,0.000000,1.836735,0.000000
4,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000


In [80]:
df_current = df1.copy()

missing_positions = [
    (1, 0),
    (3, 1),
    (49, 2)
]

for iteration in range(1, 101):

    df_previous = df_current.copy()

    # ---- R&D Spend (row 1) ----
    X = df_current.iloc[[0, 2, 3, 4], [1, 2]]
    y = df_current.iloc[[0, 2, 3, 4], 0]

    lr = LinearRegression()
    lr.fit(X, y)

    df_current.iloc[1, 0] = lr.predict(
        df_current.iloc[1, [1, 2]].values.reshape(1, 2)
    )[0]

    # ---- Administration (row 3) ----
    X = df_current.iloc[[0, 1, 2, 4], [0, 2]]
    y = df_current.iloc[[0, 1, 2, 4], 1]

    lr = LinearRegression()
    lr.fit(X, y)

    df_current.iloc[3, 1] = lr.predict(
        df_current.iloc[3, [0, 2]].values.reshape(1, 2)
    )[0]

    # ---- Marketing Spend (row 49) ----
    X = df_current.iloc[0:49, [0, 1]]
    y = df_current.iloc[0:49, 2]

    lr = LinearRegression()
    lr.fit(X, y)

    df_current.iloc[49, 2] = lr.predict(
        df_current.iloc[49, [0, 1]].values.reshape(1, 2)
    )[0]

    # Calculate change from previous iteration
    diff = np.abs(
        df_current.iloc[[1, 3, 49], :] -
        df_previous.iloc[[1, 3, 49], :]
    ).sum().sum()

    print(f"Iteration {iteration}: difference = {diff}")

    # Stop when changes are almost zero
    if diff < 1e-6:
        print("Converged!")
        break

/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature 

Iteration 1: difference = 4.248061164187506
Iteration 2: difference = 2.433578003806389
Iteration 3: difference = 0.6111729716970711
Iteration 4: difference = 0.12294519342525767
Iteration 5: difference = 0.06027425433134859
Iteration 6: difference = 0.028426749528009054
Iteration 7: difference = 0.013114736378890157
Iteration 8: difference = 0.00598381302105544
Iteration 9: difference = 0.002715874436397314
Iteration 10: difference = 0.0012296574596444287
Iteration 11: difference = 0.0005561294742566503
Iteration 12: difference = 0.0002513903137533191
Iteration 13: difference = 0.00011361140722421226
Iteration 14: difference = 5.133936105572445e-05
Iteration 15: difference = 2.319843522080589e-05
Iteration 16: difference = 1.048232827294271e-05
Iteration 17: difference = 4.736446983955034e-06
Iteration 18: difference = 2.1401574556989544e-06
Iteration 19: difference = 9.67025517439879e-07
Converged!


/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/home/malikahmadrasheed/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature 

In [81]:
df_current.iloc[[1, 3, 49]]

,R&D Spend,Administration,Marketing Spend
1,16.6,15.0,44.000000
3,14.0,8.0,38.000000
49,0.0,12.0,6.178452


In [83]:
df_current - df_previous

,R&D Spend,Administration,Marketing Spend
0,0.000000e+00,0.000000e+00,0.000000e+00
1,3.521881e-07,0.000000e+00,0.000000e+00
2,0.000000e+00,0.000000e+00,0.000000e+00
3,0.000000e+00,6.054062e-07,0.000000e+00
4,0.000000e+00,0.000000e+00,0.000000e+00
5,0.000000e+00,0.000000e+00,0.000000e+00
6,0.000000e+00,0.000000e+00,0.000000e+00
7,0.000000e+00,0.000000e+00,0.000000e+00
8,0.000000e+00,0.000000e+00,0.000000e+00
9,0.000000e+00,0.000000e+00,0.000000e+00
